# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJykTXD3Z_vaVy6NNMhexis7ovN5cC6I
"""

def kasallik_tashxisi(belgi):
  if belgi == "istima":
    return "Parastemol iching "
  elif belgi=="bosh ogrigi":
    return "bolnol"
  elif belgi=="tish ogrigi":
    return "sinipar"
  if belgi=="BMW NARXI":
    return "20000$"
  elif belgi=="MERSIDES BENS NARXI":
    return "21000$"
  elif belgi=="COBLT  NARXI":
    return "12000$"
  elif belgi=="JENTRA NARXI":
    return "5000$"
  elif belgi=="JENTRA NARXI":
    return "5000$"
  elif belgi=="NEXIA  NARXI":
    return "9000$"
  elif belgi=="MONZA NARXI":
    return "18000$"
  elif belgi=="ONX   NARXI":
    return "17000$"
  elif belgi=="TAXOE NARXI":
    return "100000$"
  elif belgi=="GELIK NARXI":
    return "350000$"
  else:
    return "shifokorga murojat qilin"
  belgi =input ("kasallik belgisini kiritin")
  natija=kasallik_tashxisi(belgi)
  print(natija)